version: "3.8"

services:
  doggydoor:
    build: .
    image: doggydoor:latest
    container_name: doggydoor-app
    # Run the main doggy door application
    command: python src/main.py
    # Mount the current directory for development
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - /var/run/dbus:/var/run/dbus # D-Bus for Bluetooth communication
    # Environment variables
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    # Network configuration for HomeKit
    network_mode: host
    # Privileged mode for Bluetooth access
    privileged: true
    # Device access for Bluetooth
    devices:
      - /dev/bus/usb:/dev/bus/usb
    # Restart policy
    restart: unless-stopped
